http:
  routers:
    frontend:
      rule: "PathPrefix(`/`)"
      service: frontend
      entryPoints: [web]

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
