"""add message parent_id

Revision ID: 039a639fc3d2
Revises: 017
Create Date: 2026-03-13 23:26:32.386258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '039a639fc3d2'
down_revision: Union[str, None] = '017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属用户 ID，级联删除',
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='对话标题，默认 New Conversation',
               existing_nullable=False,
               existing_server_default=sa.text("'New Conversation'::character varying"))
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_conversations_workspace_id'), 'conversations', type_='foreignkey')
    op.drop_table_comment(
        'conversations',
        existing_comment='对话表：每条记录代表一个对话会话',
        schema=None
    )
    op.drop_constraint(op.f('fk_cron_jobs_workspace_id'), 'cron_jobs', type_='foreignkey')
    op.alter_column('documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='文档切片数量，向量化后回填',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('documents', 'qdrant_collection',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Qdrant 中对应的 Collection 名称，格式 user_{user_id}',
               existing_nullable=False)
    op.alter_column('documents', 'minio_object_key',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='MinIO 中的对象路径，格式 {user_id}/{uuid}_{filename}',
               existing_nullable=False)
    op.alter_column('documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='软删除标记',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_documents_is_deleted'), table_name='documents', postgresql_where='(NOT is_deleted)')
    op.drop_index(op.f('idx_documents_user_id'), table_name='documents')
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_documents_workspace_id'), 'documents', type_='foreignkey')
    op.drop_table_comment(
        'documents',
        existing_comment='文档表：用户上传的知识库文档元数据',
        schema=None
    )
    op.drop_index(op.f('ix_invitations_email_lower'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.drop_index(op.f('idx_job_executions_fired_at'), table_name='job_executions')
    op.drop_index(op.f('idx_job_executions_job_id'), table_name='job_executions')
    op.create_index(op.f('ix_job_executions_fired_at'), 'job_executions', ['fired_at'], unique=False)
    op.create_index(op.f('ix_job_executions_job_id'), 'job_executions', ['job_id'], unique=False)
    op.add_column('messages', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='角色：human（用户）/ ai（AI 回复）/ tool（工具结果）/ system（系统提示）',
               existing_nullable=False)
    op.alter_column('messages', 'tool_calls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='工具调用详情 JSON，仅 role=ai 时可能非空',
               existing_nullable=True)
    op.alter_column('messages', 'tokens_input',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='输入 token 数，用于用量统计',
               existing_nullable=True)
    op.alter_column('messages', 'tokens_output',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='输出 token 数，用于用量统计',
               existing_nullable=True)
    op.drop_index(op.f('idx_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_created_at'), table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_parent_id'), 'messages', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_table_comment(
        'messages',
        existing_comment='消息表：存储对话中每条消息及 token 统计',
        schema=None
    )
    op.alter_column('user_settings', 'model_provider',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='LLM 提供商标识：deepseek / openai / anthropic',
               existing_nullable=False,
               existing_server_default=sa.text("'deepseek'::character varying"))
    op.alter_column('user_settings', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='模型名称：deepseek-chat / gpt-4 / claude-3 等',
               existing_nullable=False,
               existing_server_default=sa.text("'deepseek-chat'::character varying"))
    op.alter_column('user_settings', 'api_keys',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Fernet 加密后的 API Key JSON，格式 {"provider": "encrypted_key"}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('user_settings', 'enabled_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='已启用工具列表 JSON 数组',
               existing_nullable=False,
               existing_server_default=sa.text('\'["search", "code_exec", "file", "datetime"]\'::jsonb'))
    op.alter_column('user_settings', 'persona_override',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='用户自定义 AI 人格/系统提示词，为空时使用默认',
               existing_nullable=True)
    op.drop_table_comment(
        'user_settings',
        existing_comment='用户设置表：每用户一行，存储模型偏好和 API Key',
        schema=None
    )
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='主键，UUID v4',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='邮箱地址，全局唯一，用于登录',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='bcrypt 哈希后的密码',
               existing_nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='显示名称，可选',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='账户是否激活',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'users',
        existing_comment='用户表：存储用户基本信息和认证数据',
        schema=None
    )
    op.drop_index(op.f('idx_webhook_deliveries_triggered_at'), table_name='webhook_deliveries')
    op.drop_index(op.f('idx_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    op.drop_constraint(op.f('fk_webhooks_workspace_id'), 'webhooks', type_='foreignkey')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_webhooks_workspace_id'), 'webhooks', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.create_index(op.f('idx_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    op.create_index(op.f('idx_webhook_deliveries_triggered_at'), 'webhook_deliveries', [sa.literal_column('triggered_at DESC')], unique=False)
    op.create_table_comment(
        'users',
        '用户表：存储用户基本信息和认证数据',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='账户是否激活',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='显示名称，可选',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt 哈希后的密码',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='邮箱地址，全局唯一，用于登录',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='主键，UUID v4',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_table_comment(
        'user_settings',
        '用户设置表：每用户一行，存储模型偏好和 API Key',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_settings', 'persona_override',
               existing_type=sa.TEXT(),
               comment='用户自定义 AI 人格/系统提示词，为空时使用默认',
               existing_nullable=True)
    op.alter_column('user_settings', 'enabled_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='已启用工具列表 JSON 数组',
               existing_nullable=False,
               existing_server_default=sa.text('\'["search", "code_exec", "file", "datetime"]\'::jsonb'))
    op.alter_column('user_settings', 'api_keys',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Fernet 加密后的 API Key JSON，格式 {"provider": "encrypted_key"}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('user_settings', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment='模型名称：deepseek-chat / gpt-4 / claude-3 等',
               existing_nullable=False,
               existing_server_default=sa.text("'deepseek-chat'::character varying"))
    op.alter_column('user_settings', 'model_provider',
               existing_type=sa.VARCHAR(length=50),
               comment='LLM 提供商标识：deepseek / openai / anthropic',
               existing_nullable=False,
               existing_server_default=sa.text("'deepseek'::character varying"))
    op.create_table_comment(
        'messages',
        '消息表：存储对话中每条消息及 token 统计',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_parent_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index(op.f('idx_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('idx_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.alter_column('messages', 'tokens_output',
               existing_type=sa.INTEGER(),
               comment='输出 token 数，用于用量统计',
               existing_nullable=True)
    op.alter_column('messages', 'tokens_input',
               existing_type=sa.INTEGER(),
               comment='输入 token 数，用于用量统计',
               existing_nullable=True)
    op.alter_column('messages', 'tool_calls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='工具调用详情 JSON，仅 role=ai 时可能非空',
               existing_nullable=True)
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='角色：human（用户）/ ai（AI 回复）/ tool（工具结果）/ system（系统提示）',
               existing_nullable=False)
    op.drop_column('messages', 'parent_id')
    op.drop_index(op.f('ix_job_executions_job_id'), table_name='job_executions')
    op.drop_index(op.f('ix_job_executions_fired_at'), table_name='job_executions')
    op.create_index(op.f('idx_job_executions_job_id'), 'job_executions', ['job_id'], unique=False)
    op.create_index(op.f('idx_job_executions_fired_at'), 'job_executions', [sa.literal_column('fired_at DESC')], unique=False)
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=False)
    op.create_index(op.f('ix_invitations_email_lower'), 'invitations', [sa.literal_column('lower(email::text)')], unique=False)
    op.create_table_comment(
        'documents',
        '文档表：用户上传的知识库文档元数据',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('fk_documents_workspace_id'), 'documents', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.create_index(op.f('idx_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_index(op.f('idx_documents_is_deleted'), 'documents', ['user_id', 'is_deleted'], unique=False, postgresql_where='(NOT is_deleted)')
    op.alter_column('documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='软删除标记',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('documents', 'minio_object_key',
               existing_type=sa.VARCHAR(length=500),
               comment='MinIO 中的对象路径，格式 {user_id}/{uuid}_{filename}',
               existing_nullable=False)
    op.alter_column('documents', 'qdrant_collection',
               existing_type=sa.VARCHAR(length=255),
               comment='Qdrant 中对应的 Collection 名称，格式 user_{user_id}',
               existing_nullable=False)
    op.alter_column('documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               comment='文档切片数量，向量化后回填',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_foreign_key(op.f('fk_cron_jobs_workspace_id'), 'cron_jobs', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.create_table_comment(
        'conversations',
        '对话表：每条记录代表一个对话会话',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('fk_conversations_workspace_id'), 'conversations', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='对话标题，默认 New Conversation',
               existing_nullable=False,
               existing_server_default=sa.text("'New Conversation'::character varying"))
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               comment='所属用户 ID，级联删除',
               existing_nullable=False)
    # ### end Alembic commands ###
