"""add message parent_id # noqa: E501
 # noqa: E501
Revision ID: 039a639fc3d2 # noqa: E501
Revises: 017 # noqa: E501
Create Date: 2026-03-13 23:26:32.386258 # noqa: E501
 # noqa: E501
"""  # noqa: E501

from collections.abc import Sequence  # noqa: E501

# noqa: E501
import sqlalchemy as sa  # noqa: E501
from sqlalchemy.dialects import postgresql  # noqa: E501

# noqa: E501
from alembic import op  # noqa: E501

# noqa: E501
# revision identifiers, used by Alembic. # noqa: E501
revision: str = "039a639fc3d2"  # noqa: E501
down_revision: str | None = "017"  # noqa: E501
branch_labels: str | Sequence[str] | None = None  # noqa: E501
depends_on: str | Sequence[str] | None = None  # noqa: E501


# noqa: E501
# noqa: E501
def upgrade() -> None:  # noqa: E501
    # ### commands auto generated by Alembic - please adjust! ### # noqa: E501
    op.alter_column(
        "conversations",
        "user_id",  # noqa: E501
        existing_type=sa.UUID(),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="所属用户 ID，级联删除",  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    op.alter_column(
        "conversations",
        "title",  # noqa: E501
        existing_type=sa.VARCHAR(length=255),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="对话标题，默认 New Conversation",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("'New Conversation'::character varying"),
    )  # noqa: E501
    op.drop_index(op.f("idx_conversations_user_id"), table_name="conversations")  # noqa: E501
    op.create_index(
        op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False
    )  # noqa: E501
    op.drop_constraint(
        op.f("fk_conversations_workspace_id"), "conversations", type_="foreignkey"
    )  # noqa: E501
    op.drop_table_comment(  # noqa: E501
        "conversations",  # noqa: E501
        existing_comment="对话表：每条记录代表一个对话会话",  # noqa: E501
        schema=None,  # noqa: E501
    )  # noqa: E501
    op.drop_constraint(
        op.f("fk_cron_jobs_workspace_id"), "cron_jobs", type_="foreignkey"
    )  # noqa: E501
    op.alter_column(
        "documents",
        "chunk_count",  # noqa: E501
        existing_type=sa.INTEGER(),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="文档切片数量，向量化后回填",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("0"),
    )  # noqa: E501
    op.alter_column(
        "documents",
        "qdrant_collection",  # noqa: E501
        existing_type=sa.VARCHAR(length=255),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="Qdrant 中对应的 Collection 名称，格式 user_{user_id}",  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    op.alter_column(
        "documents",
        "minio_object_key",  # noqa: E501
        existing_type=sa.VARCHAR(length=500),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="MinIO 中的对象路径，格式 {user_id}/{uuid}_{filename}",  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    op.alter_column(
        "documents",
        "is_deleted",  # noqa: E501
        existing_type=sa.BOOLEAN(),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="软删除标记",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("false"),
    )  # noqa: E501
    op.drop_index(
        op.f("idx_documents_is_deleted"),
        table_name="documents",
        postgresql_where="(NOT is_deleted)",
    )  # noqa: E501
    op.drop_index(op.f("idx_documents_user_id"), table_name="documents")  # noqa: E501
    op.create_index(
        op.f("ix_documents_user_id"), "documents", ["user_id"], unique=False
    )  # noqa: E501
    op.drop_constraint(
        op.f("fk_documents_workspace_id"), "documents", type_="foreignkey"
    )  # noqa: E501
    op.drop_table_comment(  # noqa: E501
        "documents",  # noqa: E501
        existing_comment="文档表：用户上传的知识库文档元数据",  # noqa: E501
        schema=None,  # noqa: E501
    )  # noqa: E501
    op.drop_index(op.f("ix_invitations_email_lower"), table_name="invitations")  # noqa: E501
    op.drop_index(op.f("ix_invitations_token"), table_name="invitations")  # noqa: E501
    op.create_index(
        op.f("ix_invitations_email"), "invitations", ["email"], unique=False
    )  # noqa: E501
    op.drop_index(op.f("idx_job_executions_fired_at"), table_name="job_executions")  # noqa: E501
    op.drop_index(op.f("idx_job_executions_job_id"), table_name="job_executions")  # noqa: E501
    op.create_index(
        op.f("ix_job_executions_fired_at"), "job_executions", ["fired_at"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_job_executions_job_id"), "job_executions", ["job_id"], unique=False
    )  # noqa: E501
    op.add_column("messages", sa.Column("parent_id", sa.UUID(), nullable=True))  # noqa: E501
    op.alter_column(
        "messages",
        "role",  # noqa: E501
        existing_type=sa.VARCHAR(length=20),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="角色：human（用户）/ ai（AI 回复）/ tool（工具结果）/ system（系统提示）",  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    op.alter_column(
        "messages",
        "tool_calls",  # noqa: E501
        existing_type=postgresql.JSONB(astext_type=sa.Text()),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="工具调用详情 JSON，仅 role=ai 时可能非空",  # noqa: E501
        existing_nullable=True,
    )  # noqa: E501
    op.alter_column(
        "messages",
        "tokens_input",  # noqa: E501
        existing_type=sa.INTEGER(),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="输入 token 数，用于用量统计",  # noqa: E501
        existing_nullable=True,
    )  # noqa: E501
    op.alter_column(
        "messages",
        "tokens_output",  # noqa: E501
        existing_type=sa.INTEGER(),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="输出 token 数，用于用量统计",  # noqa: E501
        existing_nullable=True,
    )  # noqa: E501
    op.drop_index(op.f("idx_messages_conversation_id"), table_name="messages")  # noqa: E501
    op.drop_index(op.f("idx_messages_created_at"), table_name="messages")  # noqa: E501
    op.create_index(
        op.f("ix_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_messages_parent_id"), "messages", ["parent_id"], unique=False
    )  # noqa: E501
    op.create_foreign_key(
        None, "messages", "messages", ["parent_id"], ["id"], ondelete="SET NULL"
    )  # noqa: E501
    op.drop_table_comment(  # noqa: E501
        "messages",  # noqa: E501
        existing_comment="消息表：存储对话中每条消息及 token 统计",  # noqa: E501
        schema=None,  # noqa: E501
    )  # noqa: E501
    op.alter_column(
        "user_settings",
        "model_provider",  # noqa: E501
        existing_type=sa.VARCHAR(length=50),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="LLM 提供商标识：deepseek / openai / anthropic",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("'deepseek'::character varying"),
    )  # noqa: E501
    op.alter_column(
        "user_settings",
        "model_name",  # noqa: E501
        existing_type=sa.VARCHAR(length=100),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="模型名称：deepseek-chat / gpt-4 / claude-3 等",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("'deepseek-chat'::character varying"),
    )  # noqa: E501
    op.alter_column(
        "user_settings",
        "api_keys",  # noqa: E501
        existing_type=postgresql.JSONB(astext_type=sa.Text()),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment='Fernet 加密后的 API Key JSON，格式 {"provider": "encrypted_key"}',  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("'{}'::jsonb"),
    )  # noqa: E501
    op.alter_column(
        "user_settings",
        "enabled_tools",  # noqa: E501
        existing_type=postgresql.JSONB(astext_type=sa.Text()),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="已启用工具列表 JSON 数组",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text(
            '\'["search", "code_exec", "file", "datetime"]\'::jsonb'
        ),
    )  # noqa: E501
    op.alter_column(
        "user_settings",
        "persona_override",  # noqa: E501
        existing_type=sa.TEXT(),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="用户自定义 AI 人格/系统提示词，为空时使用默认",  # noqa: E501
        existing_nullable=True,
    )  # noqa: E501
    op.drop_table_comment(  # noqa: E501
        "user_settings",  # noqa: E501
        existing_comment="用户设置表：每用户一行，存储模型偏好和 API Key",  # noqa: E501
        schema=None,  # noqa: E501
    )  # noqa: E501
    op.alter_column(
        "users",
        "id",  # noqa: E501
        existing_type=sa.UUID(),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="主键，UUID v4",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("gen_random_uuid()"),
    )  # noqa: E501
    op.alter_column(
        "users",
        "email",  # noqa: E501
        existing_type=sa.VARCHAR(length=255),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="邮箱地址，全局唯一，用于登录",  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    op.alter_column(
        "users",
        "password_hash",  # noqa: E501
        existing_type=sa.VARCHAR(length=255),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="bcrypt 哈希后的密码",  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    op.alter_column(
        "users",
        "display_name",  # noqa: E501
        existing_type=sa.VARCHAR(length=100),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="显示名称，可选",  # noqa: E501
        existing_nullable=True,
    )  # noqa: E501
    op.alter_column(
        "users",
        "is_active",  # noqa: E501
        existing_type=sa.BOOLEAN(),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="账户是否激活",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("true"),
    )  # noqa: E501
    op.alter_column(
        "users",
        "created_at",  # noqa: E501
        existing_type=postgresql.TIMESTAMP(timezone=True),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="创建时间",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("now()"),
    )  # noqa: E501
    op.alter_column(
        "users",
        "updated_at",  # noqa: E501
        existing_type=postgresql.TIMESTAMP(timezone=True),  # noqa: E501
        comment=None,  # noqa: E501
        existing_comment="最后更新时间",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("now()"),
    )  # noqa: E501
    op.drop_table_comment(  # noqa: E501
        "users",  # noqa: E501
        existing_comment="用户表：存储用户基本信息和认证数据",  # noqa: E501
        schema=None,  # noqa: E501
    )  # noqa: E501
    op.drop_index(
        op.f("idx_webhook_deliveries_triggered_at"), table_name="webhook_deliveries"
    )  # noqa: E501
    op.drop_index(
        op.f("idx_webhook_deliveries_webhook_id"), table_name="webhook_deliveries"
    )  # noqa: E501
    op.create_index(
        op.f("ix_webhook_deliveries_webhook_id"),
        "webhook_deliveries",
        ["webhook_id"],
        unique=False,
    )  # noqa: E501
    op.drop_constraint(op.f("fk_webhooks_workspace_id"), "webhooks", type_="foreignkey")  # noqa: E501
    op.drop_index(op.f("ix_workspace_members_user_id"), table_name="workspace_members")  # noqa: E501
    op.drop_index(
        op.f("ix_workspace_members_workspace_id"), table_name="workspace_members"
    )  # noqa: E501
    # ### end Alembic commands ### # noqa: E501


# noqa: E501
# noqa: E501
def downgrade() -> None:  # noqa: E501
    # ### commands auto generated by Alembic - please adjust! ### # noqa: E501
    op.create_index(
        op.f("ix_workspace_members_workspace_id"),
        "workspace_members",
        ["workspace_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("ix_workspace_members_user_id"),
        "workspace_members",
        ["user_id"],
        unique=False,
    )  # noqa: E501
    op.create_foreign_key(
        op.f("fk_webhooks_workspace_id"),
        "webhooks",
        "workspaces",
        ["workspace_id"],
        ["id"],
        ondelete="SET NULL",
    )  # noqa: E501
    op.drop_index(
        op.f("ix_webhook_deliveries_webhook_id"), table_name="webhook_deliveries"
    )  # noqa: E501
    op.create_index(
        op.f("idx_webhook_deliveries_webhook_id"),
        "webhook_deliveries",
        ["webhook_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        op.f("idx_webhook_deliveries_triggered_at"),
        "webhook_deliveries",
        [sa.literal_column("triggered_at DESC")],
        unique=False,
    )  # noqa: E501
    op.create_table_comment(  # noqa: E501
        "users",  # noqa: E501
        "用户表：存储用户基本信息和认证数据",  # noqa: E501
        existing_comment=None,  # noqa: E501
        schema=None,  # noqa: E501
    )  # noqa: E501
    op.alter_column(
        "users",
        "updated_at",  # noqa: E501
        existing_type=postgresql.TIMESTAMP(timezone=True),  # noqa: E501
        comment="最后更新时间",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("now()"),
    )  # noqa: E501
    op.alter_column(
        "users",
        "created_at",  # noqa: E501
        existing_type=postgresql.TIMESTAMP(timezone=True),  # noqa: E501
        comment="创建时间",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("now()"),
    )  # noqa: E501
    op.alter_column(
        "users",
        "is_active",  # noqa: E501
        existing_type=sa.BOOLEAN(),  # noqa: E501
        comment="账户是否激活",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("true"),
    )  # noqa: E501
    op.alter_column(
        "users",
        "display_name",  # noqa: E501
        existing_type=sa.VARCHAR(length=100),  # noqa: E501
        comment="显示名称，可选",  # noqa: E501
        existing_nullable=True,
    )  # noqa: E501
    op.alter_column(
        "users",
        "password_hash",  # noqa: E501
        existing_type=sa.VARCHAR(length=255),  # noqa: E501
        comment="bcrypt 哈希后的密码",  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    op.alter_column(
        "users",
        "email",  # noqa: E501
        existing_type=sa.VARCHAR(length=255),  # noqa: E501
        comment="邮箱地址，全局唯一，用于登录",  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    op.alter_column(
        "users",
        "id",  # noqa: E501
        existing_type=sa.UUID(),  # noqa: E501
        comment="主键，UUID v4",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("gen_random_uuid()"),
    )  # noqa: E501
    op.create_table_comment(  # noqa: E501
        "user_settings",  # noqa: E501
        "用户设置表：每用户一行，存储模型偏好和 API Key",  # noqa: E501
        existing_comment=None,  # noqa: E501
        schema=None,  # noqa: E501
    )  # noqa: E501
    op.alter_column(
        "user_settings",
        "persona_override",  # noqa: E501
        existing_type=sa.TEXT(),  # noqa: E501
        comment="用户自定义 AI 人格/系统提示词，为空时使用默认",  # noqa: E501
        existing_nullable=True,
    )  # noqa: E501
    op.alter_column(
        "user_settings",
        "enabled_tools",  # noqa: E501
        existing_type=postgresql.JSONB(astext_type=sa.Text()),  # noqa: E501
        comment="已启用工具列表 JSON 数组",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text(
            '\'["search", "code_exec", "file", "datetime"]\'::jsonb'
        ),
    )  # noqa: E501
    op.alter_column(
        "user_settings",
        "api_keys",  # noqa: E501
        existing_type=postgresql.JSONB(astext_type=sa.Text()),  # noqa: E501
        comment='Fernet 加密后的 API Key JSON，格式 {"provider": "encrypted_key"}',  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("'{}'::jsonb"),
    )  # noqa: E501
    op.alter_column(
        "user_settings",
        "model_name",  # noqa: E501
        existing_type=sa.VARCHAR(length=100),  # noqa: E501
        comment="模型名称：deepseek-chat / gpt-4 / claude-3 等",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("'deepseek-chat'::character varying"),
    )  # noqa: E501
    op.alter_column(
        "user_settings",
        "model_provider",  # noqa: E501
        existing_type=sa.VARCHAR(length=50),  # noqa: E501
        comment="LLM 提供商标识：deepseek / openai / anthropic",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("'deepseek'::character varying"),
    )  # noqa: E501
    op.create_table_comment(  # noqa: E501
        "messages",  # noqa: E501
        "消息表：存储对话中每条消息及 token 统计",  # noqa: E501
        existing_comment=None,  # noqa: E501
        schema=None,  # noqa: E501
    )  # noqa: E501
    op.drop_constraint(None, "messages", type_="foreignkey")  # noqa: E501
    op.drop_index(op.f("ix_messages_parent_id"), table_name="messages")  # noqa: E501
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")  # noqa: E501
    op.create_index(
        op.f("idx_messages_created_at"), "messages", ["created_at"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("idx_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
    )  # noqa: E501
    op.alter_column(
        "messages",
        "tokens_output",  # noqa: E501
        existing_type=sa.INTEGER(),  # noqa: E501
        comment="输出 token 数，用于用量统计",  # noqa: E501
        existing_nullable=True,
    )  # noqa: E501
    op.alter_column(
        "messages",
        "tokens_input",  # noqa: E501
        existing_type=sa.INTEGER(),  # noqa: E501
        comment="输入 token 数，用于用量统计",  # noqa: E501
        existing_nullable=True,
    )  # noqa: E501
    op.alter_column(
        "messages",
        "tool_calls",  # noqa: E501
        existing_type=postgresql.JSONB(astext_type=sa.Text()),  # noqa: E501
        comment="工具调用详情 JSON，仅 role=ai 时可能非空",  # noqa: E501
        existing_nullable=True,
    )  # noqa: E501
    op.alter_column(
        "messages",
        "role",  # noqa: E501
        existing_type=sa.VARCHAR(length=20),  # noqa: E501
        comment="角色：human（用户）/ ai（AI 回复）/ tool（工具结果）/ system（系统提示）",  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    op.drop_column("messages", "parent_id")  # noqa: E501
    op.drop_index(op.f("ix_job_executions_job_id"), table_name="job_executions")  # noqa: E501
    op.drop_index(op.f("ix_job_executions_fired_at"), table_name="job_executions")  # noqa: E501
    op.create_index(
        op.f("idx_job_executions_job_id"), "job_executions", ["job_id"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("idx_job_executions_fired_at"),
        "job_executions",
        [sa.literal_column("fired_at DESC")],
        unique=False,
    )  # noqa: E501
    op.drop_index(op.f("ix_invitations_email"), table_name="invitations")  # noqa: E501
    op.create_index(
        op.f("ix_invitations_token"), "invitations", ["token"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("ix_invitations_email_lower"),
        "invitations",
        [sa.literal_column("lower(email::text)")],
        unique=False,
    )  # noqa: E501
    op.create_table_comment(  # noqa: E501
        "documents",  # noqa: E501
        "文档表：用户上传的知识库文档元数据",  # noqa: E501
        existing_comment=None,  # noqa: E501
        schema=None,  # noqa: E501
    )  # noqa: E501
    op.create_foreign_key(
        op.f("fk_documents_workspace_id"),
        "documents",
        "workspaces",
        ["workspace_id"],
        ["id"],
        ondelete="SET NULL",
    )  # noqa: E501
    op.drop_index(op.f("ix_documents_user_id"), table_name="documents")  # noqa: E501
    op.create_index(
        op.f("idx_documents_user_id"), "documents", ["user_id"], unique=False
    )  # noqa: E501
    op.create_index(
        op.f("idx_documents_is_deleted"),
        "documents",
        ["user_id", "is_deleted"],
        unique=False,
        postgresql_where="(NOT is_deleted)",
    )  # noqa: E501
    op.alter_column(
        "documents",
        "is_deleted",  # noqa: E501
        existing_type=sa.BOOLEAN(),  # noqa: E501
        comment="软删除标记",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("false"),
    )  # noqa: E501
    op.alter_column(
        "documents",
        "minio_object_key",  # noqa: E501
        existing_type=sa.VARCHAR(length=500),  # noqa: E501
        comment="MinIO 中的对象路径，格式 {user_id}/{uuid}_{filename}",  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    op.alter_column(
        "documents",
        "qdrant_collection",  # noqa: E501
        existing_type=sa.VARCHAR(length=255),  # noqa: E501
        comment="Qdrant 中对应的 Collection 名称，格式 user_{user_id}",  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    op.alter_column(
        "documents",
        "chunk_count",  # noqa: E501
        existing_type=sa.INTEGER(),  # noqa: E501
        comment="文档切片数量，向量化后回填",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("0"),
    )  # noqa: E501
    op.create_foreign_key(
        op.f("fk_cron_jobs_workspace_id"),
        "cron_jobs",
        "workspaces",
        ["workspace_id"],
        ["id"],
        ondelete="SET NULL",
    )  # noqa: E501
    op.create_table_comment(  # noqa: E501
        "conversations",  # noqa: E501
        "对话表：每条记录代表一个对话会话",  # noqa: E501
        existing_comment=None,  # noqa: E501
        schema=None,  # noqa: E501
    )  # noqa: E501
    op.create_foreign_key(
        op.f("fk_conversations_workspace_id"),
        "conversations",
        "workspaces",
        ["workspace_id"],
        ["id"],
        ondelete="SET NULL",
    )  # noqa: E501
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")  # noqa: E501
    op.create_index(
        op.f("idx_conversations_user_id"), "conversations", ["user_id"], unique=False
    )  # noqa: E501
    op.alter_column(
        "conversations",
        "title",  # noqa: E501
        existing_type=sa.VARCHAR(length=255),  # noqa: E501
        comment="对话标题，默认 New Conversation",  # noqa: E501
        existing_nullable=False,  # noqa: E501
        existing_server_default=sa.text("'New Conversation'::character varying"),
    )  # noqa: E501
    op.alter_column(
        "conversations",
        "user_id",  # noqa: E501
        existing_type=sa.UUID(),  # noqa: E501
        comment="所属用户 ID，级联删除",  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    # ### end Alembic commands ### # noqa: E501
