"""add_persona_override_to_conversation

Revision ID: 8a5a139f45c7
Revises: 6c691c025f2e
Create Date: 2026-03-15 14:11:17.362745

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a5a139f45c7"
down_revision: str | None = "6c691c025f2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations", sa.Column("persona_override", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "persona_override")
    # ### end Alembic commands ###
