"""add_workflow_dsl_to_conversation

Revision ID: fdcf42e184ee
Revises: 8a5a139f45c7
Create Date: 2026-03-15 15:23:57.065384

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdcf42e184ee"
down_revision: str | None = "8a5a139f45c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "workflow_dsl", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "workflow_dsl")
    # ### end Alembic commands ###
