#!/usr/bin/env bash
# Generate a secure .env file with random credentials.
# Usage: bash scripts/init-env.sh
set -euo pipefail

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
    echo "⚠  $ENV_FILE already exists — skipping to avoid overwriting."
    echo "   Delete it first if you want to regenerate."
    exit 0
fi

# Warn if persistent data directories already exist (passwords are baked into
# the data on first run; a newly generated .env will have different passwords).
DATA_DIR="${HOME}/jarvis-data"
if [ -d "$DATA_DIR/postgres" ] || [ -d "$DATA_DIR/redis" ] || [ -d "$DATA_DIR/minio" ]; then
    echo ""
    echo "⚠  Existing data detected in $DATA_DIR"
    echo "   Passwords are set during first database initialization."
    echo "   A new .env will contain different random passwords, causing auth failures."
    echo ""
    echo "   Options:"
    echo "     1) Delete old data:  rm -rf $DATA_DIR"
    echo "     2) Reuse old .env:   copy the previous .env into this directory"
    echo ""
    read -r -p "   Continue generating a new .env anyway? [y/N] " ans || true
    case "$ans" in
        [yY]*) ;;
        *) echo "   Aborted."; exit 0 ;;
    esac
fi

rand_password() { openssl rand -hex 18; }

# Fernet key — use uv to pull cryptography on-demand (no pre-install required).
gen_fernet_key() {
    local cmd='from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())'
    uv run --with cryptography python -c "$cmd"
}

POSTGRES_PASSWORD=$(rand_password)
MINIO_ACCESS_KEY="minioadmin"
MINIO_SECRET_KEY=$(rand_password)
REDIS_PASSWORD=$(rand_password)
JWT_SECRET=$(rand_password)
ENCRYPTION_KEY=$(gen_fernet_key)
GRAFANA_PASSWORD=$(rand_password)

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/init-env.sh — $(date -Iseconds)

# Database
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql+asyncpg://jarvis:${POSTGRES_PASSWORD}@localhost:5432/jarvis

# Object storage (MinIO)
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
MINIO_ENDPOINT=localhost:9000
MINIO_BUCKET=jarvis-documents

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379

# Authentication
JWT_SECRET=${JWT_SECRET}

# Fernet encryption key
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Monitoring
GRAFANA_USER=admin
GRAFANA_PASSWORD=${GRAFANA_PASSWORD}

# LLM API Keys — fill in at least one key to enable chat
DEEPSEEK_API_KEY=
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
ZHIPUAI_API_KEY=

# Optional Tools
TAVILY_API_KEY=
EOF

echo "✅  $ENV_FILE created. Open it and fill in at least one LLM API key."

# Install git hooks (commit + push stages)
if command -v pre-commit &> /dev/null; then
  pre-commit install
  pre-commit install --hook-type pre-push
  echo "✅  pre-commit hooks installed (commit + push stages)."
fi
