#!/usr/bin/env bash
# Generate a secure .env file with random credentials.
# Usage: bash scripts/init-env.sh
set -euo pipefail

ENV_FILE="${1:-.env}"

if [ -f "$ENV_FILE" ]; then
    echo "⚠  $ENV_FILE already exists — skipping to avoid overwriting."
    echo "   Delete it first if you want to regenerate."
    exit 0
fi

rand_password() { openssl rand -hex 18; }

# Fernet key requires the cryptography package.
# Try the project venv first, then fall back to system python3.
gen_fernet_key() {
    local cmd='from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())'
    if [ -f ".venv/bin/python" ]; then
        .venv/bin/python -c "$cmd" 2>/dev/null && return
    fi
    python3 -c "$cmd" 2>/dev/null && return
    echo "ERROR: 'cryptography' package not found." >&2
    echo "  Install it with:  uv sync  (or)  pip install cryptography" >&2
    exit 1
}

POSTGRES_PASSWORD=$(rand_password)
MINIO_ROOT_USER="minioadmin"
MINIO_ROOT_PASSWORD=$(rand_password)
REDIS_PASSWORD=$(rand_password)
JWT_SECRET=$(rand_password)
ENCRYPTION_KEY=$(gen_fernet_key)

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/init-env.sh — $(date -Iseconds)

# Database
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Object storage
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}

# Authentication
JWT_SECRET=${JWT_SECRET}

# Fernet encryption key
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# LLM — fill in your API key
DEEPSEEK_API_KEY=

# Composed URLs — for local dev (docker-compose overrides these with container hostnames)
DATABASE_URL=postgresql+asyncpg://jarvis:${POSTGRES_PASSWORD}@localhost:5432/jarvis
REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379
EOF

echo "✅  $ENV_FILE created. Review it and fill in DEEPSEEK_API_KEY."
